### ISSUE TITLE
feat: footer year can be updated to 2023

### ISSUE THREAD

**Issue by baekusboo** [Your-First-Open-Source-Project/main-website#108]
The year in the footer can be changed from 2022 to 2023

<img width="937" alt="image" src="https://github.com/Your-First-Open-Source-Project/main-website/assets/83155556/d2a6fc9d-2088-47aa-bd96-2e9a01952da2">

**Comment by melvincwng** [comment]
@baekusboo, this issue is not required as the community website was indeed made during Hacktoberfest 2022.

Closing this ticket.
