### ISSUE TITLE
Add new members as of 03/10/2023

### ISSUE THREAD

**Issue by melvincwng** [Your-First-Open-Source-Project/main-website#110]
To add members who recently joined the organization into the community website (as of 03/10/2023)

**Comment by Baburao-sanivada** [comment]
I want to Work on the Issue And Where Can i Get the Data of New Members to be Added

**Comment by melvincwng** [comment]
@Baburao-sanivada, I will be working on this issue. 

Stay tuned for issues that will be added for Hacktoberfest 2023
