### ISSUE TITLE
Fix member count in the community website

### ISSUE THREAD

**Issue by melvincwng** [Your-First-Open-Source-Project/main-website#112]
**Issue:** 

- The member count in the community website is outdated. 

- We currently have 178 members.

**Suggested change**:

- To change the member count from `170+` to `178+` (**Take note**: There are **two** places to change in the codebase)

- This is a fairly simple issue and is good for beginners who wish to contribute to their 1st PR in Hacktoberfest 2023 😄 

- Ping me here if you want to take up this task

![image](https://github.com/Your-First-Open-Source-Project/main-website/assets/77479885/2f90088e-c315-4e55-a5f1-949c8bd9e50c)

**Comment by melvincwng** [comment]
@Baburao-sanivada, do you want to take up this task?

**Comment by dollarboysushil** [comment]
@melvincwng  can i take this up?

**Comment by melvincwng** [comment]
Sure @dollarboysushil, assigned it to you :)

**Comment by Baburao-sanivada** [comment]
> @Baburao-sanivada, do you want to take up this task?

yes

**Comment by melvincwng** [comment]
Hey @Baburao-sanivada, the task has already been assigned to @dollarboysushil
